# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd01b97cb6f440619cb5fa4d32c8c44dba53b138ef6d4707cb6eb6c2dff0fe51cd6003f81219a9caab6b20d86a03d1f6fbabe291601e47cdf48bd6a4a98d12b6

test:
  secret_key_base: f558846bcff4a5fb7ea06a54d295a8951de2c0ca8abae5bab8ce9cbf0e7b18bae85f54f65210ddd22f7eb2fe0fd47d3131b628e020f706182d0c2747d4b4ef2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
